-- 0009 was auto-generated by drizzle-kit after the hand-written 0007 + 0008
-- migrations (whose meta/ snapshots were never created). The diff re-emitted
-- the columns already added by 0007 (jobs.progress) and 0008 (users.address_*,
-- phone), so we use IF NOT EXISTS to make the migration idempotent and let a
-- fresh `npm run db:migrate` succeed end-to-end. The only genuinely new
-- columns here are councils.logo_url and councils.logo_bg.
ALTER TABLE "councils" ADD COLUMN IF NOT EXISTS "logo_url" text;--> statement-breakpoint
ALTER TABLE "councils" ADD COLUMN IF NOT EXISTS "logo_bg" text;--> statement-breakpoint
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "progress" jsonb DEFAULT '[]'::jsonb NOT NULL;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "address_line1" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "address_line2" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "address_city" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "address_postcode" text;--> statement-breakpoint
ALTER TABLE "users" ADD COLUMN IF NOT EXISTS "phone" text;